org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=cobblemon-skills
mod_id=cobblemon_skills
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Cobblemon Skills
mod_description=Cobblemon Skill trees, level up your trees and increase your benefits while exploring your world, and fighting, breeding, catching, and more!
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/cobblemon-skills/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/cobblemon-skills
git_url=github.com/Matthiesen-dev/cobblemon-skills
modrinth_url=https://modrinth.com/mod/cobblemon-skills

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1